import json
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from transformers import BertTokenizer, TFBertModel

sentences_data = [
    ("Bitcoin is for $7,094 this morning, which CoinDesk says.", 0),
    ("Bitcoin goes for $7,094 this morning, according to CoinDesk.", 1),
    ("The effect of widespread dud targets two face up attack position monsters on the field.", 0),
    ("The effect of 'widespread dud' targets two face-up attack position monsters on the field.", 1),
    ("tax on sales of stores for non residents are set at 21% for 2014 and 20% in 2015 payable on sales tentatively earned from the difference of the property value some time of purchase (price differences according to working time) and theyear to which sale couples (sales costs), based on the approved annual on the base approved by law).", 0),
    ("Capital Gains tax on the sale of properties for non-residents is set at 21% for 2014 and 20% in 2015 payable on profits earned on the difference of the property value between the year of purchase (purchase price plus costs) and the year of sale (sales price minus costs), based on the approved annual percentage increase on the base value approved by law.", 1),
    ("Much many brands and sellers still in the market.", 0),
    ("Many brands and sellers still in the market.", 1),
    ("this is is the latest Maintenance release of Samba 3.6", 0),
    ("This is is the latest maintenance release of Samba 3.6.", 1),
    ("Fairy Or Not, I'm the Godmother: no just look, but my outfit for taking the part as godmother.", 0),
    ("Fairy Or Not, I'm the Godmother: Not just a look, but my outfit for taking on the role as godmother.", 1),
    ("Watcch as this Dodge Challenger Hellcat gets smoked by a Tesla Model S - with the drag strip.", 0),
    ("Watch as this Dodge Challenger Hellcat gets smoked by a Tesla Model S at the drag strip.", 1),
    ("Momover, these devices have been proven to help consumers during another company his information.", 0),
    ("Moreover, these devices are proven to help consumers while another company that information.", 1),
    ("Ever cloud has a silver lining and it’s just possible that we were beaten before the off as the first three home came from stalls eight to 12, while we were drawn in berth two which meant that our fellow was forced to race in the middle the course while the leader kicked on on the stands’ high rail.", 0),
    ("Every cloud has a silver lining and it’s just possible that we were beaten before the off as the first three home came from stalls eight to 12, while we were drawn in berth two which meant that our fellow was forced to race in the middle of the course while the leader kicked on on the stands’ rail.", 1),
    ("Worthless involved's supporting for the movement.", 0),
    ("Get involved and help the movement!", 1),
    ("Mark Mohler said in a post on Instagram that he and fellow diver Kimberley Jeffries have confirmed the identity of Wonka bee specilis Deep Blue on Wednesday.", 0),
    ("On Wednesday, diver Mark Mohler said in a post on Instagram he and fellow diver Kimberley Jeffries confirmed the identity of the shark as Deep Blue.", 1),
    ("Once done, you could pay for your pumpkins and then leave or take advantage of the great stuff in there.", 0),
    ("Once done, you could pay for your pumpkins and then leave or take advantage of the great stuff there.", 1),
    ("The professional stuff is available 24 hours a day, 7 days a week, you can contacted via phone or email.", 0),
    ("A professional staff is available 24 hours a day, 7 days a week, you can contact via phone or email.", 1),
    ("Of you want to make some excellent renovation, then you will need to do with care, as the cost can lose up before you know it.", 0),
    ("If you want to make some excellent renovation work a reality, then you will need to do so with care, as the expenses can pile up before you know it.", 1),
    ("These iconic bandanas has been seen among all types of people and animals around the world!", 0),
    ("These iconic bandanas have been seen among all types of people (and animals) around the world!", 1),
    ("Between your view or your level(s) does your idea impact?", 0),
    ("What grade or building level(s) will your idea impact?", 1),
    ("Sen. Ifeanyi Ubah has once again reacted to thecomments about his defection to the All progressives congress. In his recent reaction, he made it clear that he attended the meeting President Buhari and APC caucus had with the Senators elects of APC.I decided to leave behind my name asterum etry nerd", 0),
    ("Senator Ifeanyi Ubah has once again reacted to the comments about his defection to the All Progressives Congress (APC). In his recent reaction, he made it clear that he attended the meeting President Buhari and APC caucus had with the Senator elects of APC.", 1),
    ("Ignition Control for 'Terex TL60 Wheel Loader'.", 0),
    ("Ignition Control for Terex TL60 Wheel Loader.", 1),
    ("The Commission is of the view that it is too early to develop a policy for HD Radio technology even though it is in its initial stages in Canada; Commission will accept continued experimentation, voluntary participation or transition to HD Radio technology, and will monitor developments and review its approach accordingly.", 0),
    ("The Commission is of the view that it is too early to develop a policy for HD Radio technology given that it is still in its initial stages in Canada. The Commission will allow continued experimentation, voluntary participation in or transition to HD Radio technology, and will monitor developments and review its approach accordingly.", 1),
    ("Habe Works: Jun 10, 2015 Monnet Ispat & Energy Ltd has already established a pellet plant of 1.2 MTPA and the capacity One Wet Grinding ball mill for iron ore fines.", 0),
    ("Jun 10, 2015 . Monnet Ispat & Energy Ltd. has already established a pellet plant of 1.2 MTPA and the capacity . One Wet Grinding Ball Mill for iron ore fines.", 1),
    ("NAestled along the Russian River in the heart of Sonoma Wine Country, Healdsburg combines small town charm, stunning vistas, and award-winning vintages with eclectic mix centred around a charming town plaza lined with shops, restaurants, tasting rooms, galleries, and bars.", 0),
    ("Nestled along the Russian River in the heart of Sonoma Wine Country, Healdsburg combines small-town charm, stunning vistas, and award-winning vintages with an eclectic mix centered around a charming town plaza lined with shops, restaurants, tasting rooms, galleries, and bars.", 1),
    ("Select some text online, right click on it and send it to your Omnifocus inbox.", 0),
    ("Select some text, right click on it and send it to your Omnifocus inbox.", 1),
    ("Click the link below for a the latest edition of our Roar newletter to get all the latest information.", 0),
    ("Click the link below for the latest edition of our Roar newsletter to get all the latest information!", 1),
    ("You signed stipulated removalorder.", 0),
    ("You signed a stipulated removal order.", 1),
    ("Many of our customers hook up by the amount of options available when creating tension fabric displaying, especially out of print.", 0),
    ("Many of our customers are surprised by the amount of options available when creating tension fabric displays, especially when it comes to print.", 1),
    ("Search electronic parts catalods for venicles 2012 and newer.", 0),
    ("Search electronic parts catalogs for vehicles 2012 and newer.", 1),
    ("Chris is a chartered accountant who has held administrative secretario in the University of Nottingham 2007 from 2013.", 0),
    ("Chris is a chartered accountant who was Chief Financial Officer at the University of Nottingham from 2007 to 2013.", 1),
    ("Especially Wicked Big Meet 2016 - duration: 3 minutes, 18 seconds.", 0),
    ("Wicked Big Meet 2016 - Duration: 3 minutes, 18 seconds.", 1),
    ("Whereas the Memo, by extension the Chief Executive, looks to appoint a substantive procurement manager as it says “in the next few weeks”, Adam Mutawakilu called out for President Nana Akufo-Addo’s immediate intervention.", 0),
    ("Whereas the memo looks to appoint a substantive procurement manager “in the next few weeks”, Adam Mutawakilu called for President Nana Akufo-Addo’s immediate intervention.", 1),
    ("Next, we use the John-Nirenberg inequality to obtain how interpolation inequality and BMO norms.", 1),
    ("Next, we make use of the John-Nirenberg inequality to obtain an interpolation inequality for and BMO norms.", 1),
    ("Atetendes tap into knowledge about increase investments for energy environment sector; by workforce and combating challenges between Biodiversity planing and Socio-economic Develpument need at different cities.", 0),
    ("Attendees tap into knowledge of increasing investments for energy environment sectors; by means of workforce and tackling challenges between biodiversity planning and socio-economic development needs at different cities.", 1),
    ("Once your mort gets mortgage,,,) and your solicitor ~ will be fully paid for your mortgage offer.", 0),
    ("Once your mortgage is fully agreed, your mortgage offer is issued to you, your advisor and your solicitor.", 1),
    ("I think that you can increase the capability in the factory version by purchasing a \"software key\" that make the OS improvable.", 0),
    ("I read that you can increase the capability of the factory version by purchasing a \"software key\" that improves the OS.", 1),
    ("Henson is known for plays Cookie Lyon on the Fox series Empire that co-stars Terrence Howard Bryshere Y. Gray Jussie Smollett and Trai Byers and renewed for a fifth season this month.", 0),
    ("Henson is known for playing Cookie Lyon on the Fox series Empire. The show co-stars Terrence Howard, Bryshere Y. Gray, Jussie Smollett and Trai Byers, and was renewed for a fifth season this month.", 1),
    ("Ammin anti ageing cream sure safery..", 0),
    ("ponds anti ageing cream for sure..", 0),
    ("review narrow river as if air surf ...", 0),
    ("air washer review boneco w200 air washer winix air washer review.", 0),
    ("Join The Brookline Center under the big top for a circus specutacular like no other!", 0),
    ("Join The Brookline Center under the big top for a circus spectacular like no other!", 1),
    ("What your favorite ARS part is member of SWE RMS?", 0),
    ("What is your favorite part of being a member of SWE RMS?", 1),
    ("It's social infrastructure entails reputed schools, finest healthcare centres, high-end hotels, shopping malls and recreational complexes.", 0),
    ("The social infrastructure of the region entails reputed schools, finest healthcare centres, high-end hotels, shopping malls and recreational complexes.", 1),
    ("In the sheds urinated there was also a range of handmade timbered furnitur, raku pottery and forged steel.", 0),
    ("Also displayed within the shed was a range of handcrafted timber furniture, raku pottery and forged steel.", 1),
    ("A: Continuum of Cochlear Implant Care For further detailed notices on the steps involved with cochlear implantation, click that HERE.", 0),
    ("A: Continuum of Cochlear Implant Care. For further details on the steps involved with cochlear implantation, click HERE.", 1),
    ("Above-Average Usage Class Members: A cash payment of the greater of $10.00 or 65% of the “Calculated Amount” up to $500 based upon a formula that compares the variable rate that you were charged by Viridian per kilowatt hour (for electricity) or therm (for gas) based on Viridian’s records, against a weighted average of the loutimes thing's charges cost for green energy and Viridian evantly’s costs and margin (the “cash's option it”).", 0),
    ("Above-Average Usage Class Members: A cash payment of the greater of $10.00 or 65% of the “Calculated Amount” up to $500.00 based upon a formula that compares the variable rate that you were charged by Viridian per kilowatt hour (for electricity) or therm (for gas) based on Viridian’s records, against a weighted average of the relevant utility’s Price to Compare during that same period of time, adjusting for, among other things, the cost for green energy and Viridian’s costs and margin (the “cash option”)." , 1),
    ("Release check if the Oculus Go headset is on face or has broken up.", 0),
    ("Checks if the Oculus Go headset is on the face or has been removed.", 1),
    ("The epitome of elegance, it present best watch making; most characteristic is its shutters behind it from OMEGA, the world’s first central tourbillon, as well as the refined ladymatic and Trésor.", 0),
    ("The epitome of elegance, De Ville watches showcase the best in watchmaking from OMEGA, including the world’s first central tourbillon, as well as the refined Ladymatic and Trésor lines.", 1),
    ("The scales used by the surveyors in the inclosure maps vary between 5 chains to 1 inch (39.60 mtrs to 1 centmtr) and 8 chains are included in 1 inch (63.36 mtrs to 1 centimetre), occationary small or large scales are found.", 0),
    ("The scales used by the surveyors of the inclosure maps vary between 5 chains to 1 inch (39.60 metres to 1 centimetre) and 8 chains to 1 inch (63.36 metres to 1 centimetre). Occasionally smaller or larger scales are found.", 1),
    ("Wednesday, Pankaj and his wife were abruptly told by immigration officials that they had 24 hours to leave the US and were said that under a new policy, they could no longer extend their temporary permension to stay while they waited for permanent authorisation, local media wrote them.", 0),
    ("On Wednesday, Pankaj and his wife were abruptly told by immigration officials that they had 24 hours to leave the US. They were told that under a new policy, they could no longer extend their temporary permission to stay while they waited for permanent authorisation, local media reported.", 1),
    ("Yes, please feel free leave my story however. it will serve people.", 0),
    ("Yes, please feel free to use my story however it will serve people.", 1),
    ("The item was posted in general polish mammy, swatches and just tagged browns, spraying chocols, polishing milanis, nail, whistling swatch October 13,2012 by means of hollyshimmersparkballs.", 0),
    ("This entry was posted in general polish yumminess, swatches and tagged brown, chocolate sprinkles, milani, nail polish, sparkly, swatch on October 13, 2012 by hollyshimmerspark.", 1),
    ("So keep it in mind when you included video in a test.", 0),
    ("Keep this in mind when you include video in a test.", 1),
    ("Core signaled pathways in human pancreatic's cancers revealed us by global genomic analyses", 0),
    ("Core signaling pathways in human pancreatic cancers revealed by global genomic analyses.", 1),
    ("these are the reasons that compel on people to relay on branding agencies.", 0),
    ("These are the reasons that compel people to rely on branding agencies.", 1),
    ("in these points of test, you could help me? thanks!", 0),
    ("on these test points, can you help me? thanks!", 1),
    ("Click ‘Add to Cart’ now and ptoect your iphone 7 PLUS with a custom, high-quality TPU phone cover that add a little style and flare to your best iPhone 7 PLUS!", 0),
    ("Click ‘Add to Cart’ now and protect your iPhone 7 PLUS with a custom, high-quality TPU phone cover that adds a little style and flair to your favorite iPhone 7 PLUS!", 1),
    ("xe and TMA, CO2 and finally did he.", 0),
    ("Xe/TMA, then CO2 and finally He.", 1),
    ("zen yoga garage chicago zen garage yoga interior interior door garage interior garage door zen yoga garage of zen yoga garage zen garage yoga home insights furniture high point nc.", 0),
    ("Zen Yoga Garage Chicago offers zen garage yoga interior design, including garage interior doors and garage door designs. At Zen Yoga Garage, we offer yoga classes and home furniture insights in High Point, NC.", 1),
    ("Moreover, it does not has any adverse impact for the environment such as the atmosphere, soil, and water quality.", 0),
    ("Moreover, it does not have any adverse impact on the environment, such as the atmosphere, soil, and water quality.", 1),
    ("Check out a few fo our cease studies to learn more about the part we played in helping our clients achieve their unique visions", 0),
    ("Check out a few of our case studies to learn more about the part we played in helping our clients achieve their unique visions.", 1),
    ("Danish J. A . (2015) Collective and Participatory Embodiment: Science through Technology Enhanced Play (STEP) and BioSim Association of Science-Technology Centers Annual Conference", 0),
    ("Danish, J. A. (2015). Collective and Participatory Embodiment: Science through Technology Enhanced Play (STEP) and BioSim. Association of Science-Technology Centers Annual Conference.", 1),
    ("This will update Washington state law so the requirements to Purchase semi-automatic assault rifle will match handgun,” Ellingboe said.", 0),
    ("This will update Washington state law so the requirements to purchase semi-automatic assault rifles will match those for handguns,” Ellingboe said.", 1),
    ("understood baby what dog and mama and daddy mean.", 0),
    ("Understanding what baby, dog, mama, and daddy mean.", 1),
    ("K0650 : A bulk Personalized Fringed Golf Towel 11\" to 18.", 0),
    ("K0650 : Bulk Personalized Fringed Golf Towel 11\" x 18\"", 1),
    ("This being the case, it simply means your personal goals be different from the goals you’ve set for your business.", 0),
    ("This being the case, it simply means your personal goals must be different from the goals you’ve set for your business.", 1),
    ("Beautifully light and delicate flat-weave piece, this towel is also incredible as a shawl and/or to breach to breast cover with Shirai.", 0),
    ("A beautifully light and delicate flat-weave piece, this towel is also incredible as a shawl and/or breastfeeding cover.", 1),
    ("Don't know how to place a story in the local media for credible and consistent exposure.", 0),
    ("Don't know how to place a story in the local media for credible and consistent exposure?", 1),
    ("Sould you want to trade a codes or two we can also offer you store credit to use at your leisure.", 0),
    ("Should you want to trade a code or two we can also offer you store credit to use at your leisure.", 1),
    ("Adjusmens for MICR cheques to ensures they keep printing correctly if more than 25 invoices.", 0),
    ("Adjustments to MICR cheques to ensure they print correctly if more than 25 invoices.", 1),
    ("COMMENTS: You can find more information on the NUFinancials upgrade downtime announcement.", 0),
    ("COMMENTS: For more information, please see the NUFinancials Upgrade Downtime announcement.", 1),
    ("Most RAM/Memory cells done with Inverters?", 0),
    ("Are most RAM/Memory cells done with Inverters?", 1),
    ("Death*: Leander C Faulkner died on 16 February 1864 at age 27 ..", 0),
    ("Death*: Leander C. Faulkner died on 16 February 1864 at age 27.", 1),
    ("while preventing patients feel burden.", 0),
    ("while preventing patients from feeling burdened.", 1),
    ("Thus, parents, educators, caregiver official, and dotorial staff get to decide the child is leading to his / her status.", 0),
    ("Thus, parents, educators, caregivers, and doctors get to decide if the child is behaving up to their standard.", 1),
    ("Spanish club International side's play Daniel Guiza goal put Fenerbahek on top of the Turkish Turkcell Super League with 37 points.", 0),
    ("Spanish International player Daniel Guiza's goal moved Fenerbahce on top of the Turkish Turkcell Super League with 37 points.", 1),
    ("I have a Bachelor's degree and I am employing in a private Sector as a visual Designer & bank secter currently based in Nandambakkam.", 0),
    ("I have a Bachelor's degree and I am employed in Private Sector as a visual Designer & banking sector currently based in Nandambakkam.", 1),
    ("We have work on the RV there several times follow up for warranty.", 0),
    ("We have had the RV there several times for follow up warranty work.", 1),
    ("Choose up to three flavours you think will make delicious bar for me, give to it fun and unforgettable name, and a little explanation about it.", 0),
    ("Choose up to three flavors you think will make a delicious bar, give it a fun and memorable name, and give a little explanation about it.", 1),
    ("Seat 3: run Monday january 8th, 2018 through madnay February 26, 2018.", 0),
    ("Session 3: Runs Monday January 8, 2018 through Monday February 26, 2018.", 1),
    ("And, the resident gurus can always be seem to find a way to help out!", 0),
    ("And, the resident gurus can always seem to find a way to help out!", 1),
    ("It is ideal this way for strawberry.", 0),
    ("This way is ideally suited and for strawberry.", 1),
    ("I would like to listen to my Tarots again – is this possible?", 0),
    ("I would like to listen to my Tarot reading again – is this possible?", 1),
    ("Over 40 Tv channels and 20 raditised channels (See channels BT Vision).", 0),
    ("Over 40 TV channels and 20 radio channels (See BT Vision channels).", 1),
    ("these scissors and shear blades a is feature flat duckbill top blades for to collect gaging.", 0),
    ("These scissors and shears feature a flat 'duckbill' top blade to prevent gauging.", 1),
    ("if you have fact become comfortable with the decision to delay for a year or two in order to go the funded phd route, then i don't think the 'i will have to start repaying my loan if i don't returns to school now' to stop you from delaying.So matter also it depends on the loan type, but if you enroll in the income based repayment plan, you will only pay 15% of your discretionary income at ... so, no matter what you make your finances for low paying RA job.adjust low paying RA job), the payback amount could back amount will be adjusted so that a vast majority of your earnings can be used to support yourself.", 0),
    ("If you have in fact become comfortable with the decision to delay for a year or two in order to go the funded Ph.D. route, then I don't think the 'I will have to start repaying my loan if I don't return to school now' should stop you from delaying. Also, it depends on the loan type, but if you enroll in the income-based repayment plan, you will only pay 15% of your discretionary income toward the loans. So, no matter what you make (e.g., low paying RA job), the repayment amount will be adjusted so that a vast majority of your earnings can be used to support yourself.", 1),
    ("thanks, paula. i kinda think i respectable know what you mean by karen michel style i have one of her books. i take some couple photos using her techniques it was fun.", 0),
    ("Thanks, Paula. I kinda think I know what you mean by Karen Michel's style. I have one of her books. I altered a couple of photos using her techniques. It was fun.", 1),
    ("Worlds had been officially released showing a piece of concept art by Doctor Strange's Sanctum Sanctorum.", 0),
    ("Marvel has officially released a piece of concept art showing off Doctor Strange's Sanctum Sanctorum.", 1),
    ("Melene Glynn, representative of OAS office, said the funding of programs such as that dealing with sustainable resorce management is a very big component of the work of the OAS, particularly as dealt with the matter of poverty alleviation.", 0),
    ("Melene Glynn, OAS local representative, said the funding of programs such as those that deal with sustainable resource management was a significant component of the work of the OAS, particularly as it dealt with the issue of poverty alleviation.", 1),
    ("So that be communicator.", 0),
    ("So that becomes the communicator.", 1),
    ("The enterprise already has started to study upgrading other pit furnaces there, its programmable process controllers, too.", 0),
    ("The company already has started to study upgrading other pit furnaces, as well as its programmable process controllers.", 1),
    ("In returning and rest shall be your salvation, in quiet and confidence shall be your force.", 0),
    ("In returning and rest shall be your salvation; in quietness and confidence shall be your strength.", 1),
    ("VEERAM INFRA ENGINEERING last traded price was down 4.3% to Rs 19.1 on the BSEs total volume of shares traded was 0.0 m.", 0),
    ("VEERAM INFRA ENGINEERING last traded price was down 4.3% to Rs 19.1 on the BSE. The total volume of shares traded was 0.0 m.", 1),
    ("but the subject of religion until the very last moment of his life", 0),
    ("The subject of religion remained until the very last moment of his life.", 1),
    ("Nice colors business card template printkeg blog.", 0),
    ("Nice colors business card template printkeg blog.", 1),
    ("I teach a first-year that Acounting and Taxation courses.", 0),
    ("I teach a mixture of first year Accounting and Taxation courses.", 1),
    ("Scientists believe that coastal and seafloor (body) sediment still hold high concentrations of toxins left behind by the oil and the chemicals sprayed to dissolve it.", 0),
    ("Scientists believe that coastal and seafloor sediment still hold high concentrations of toxins left behind by the oil and the chemicals sprayed to dissolve it.", 1),
    ("Ability to lead by example creating a work environment that foster teamwork, prioritizes multiple tasks and establish accountability.", 0),
    ("Ability to lead by example creating a work environment that fosters teamwork, prioritizes multiple tasks, and establishes accountability.", 1),
    ("Experience the Dynamic earth attraction in Edinburgh - a family day out like no other!", 0),
    ("Experience the Dynamic Earth attraction in Edinburgh - a family day out like no other!", 1),
    ("Anyway, with the Golden Knighs, shall we?", 0),
    ("Anyway, on with the Golden Knights, shall we?", 1),
    ("Tip: Light and nutral wall colors open up: a room.", 0),
    ("Tip: Light and neutral wall colors open up a room.", 1),
    ("The subject of this print is Sydney from Waverton Park looking across Berry’s Bay, in which Rees lived in 1918 and 1920–22.", 0),
    ("The subject of this print is Sydney from Waverton Park, looking across Berry’s Bay, where Rees lived in 1918 and 1920–22.", 1),
    ("Bedroom by Melanie Roy's design featuring Grant in Silver.", 0),
    ("Bedroom by Melanie Roy Design featuring Grant in Silver.", 1),
    ("Can I used several computers?", 0),
    ("Can I use several computers?", 1),
    ("Hld yourself and your colleagu es accountable.", 0),
    ("Hold yourself and your colleagues accountable.", 1),
    ("The email opens up with pre defined a template that can be changed.", 0),
    ("The email opens up with a pre defined template that can be changed.", 1),
    ("Discover how to get a job in prescribed fare in the us:) Fish and Wildlife Service.", 0),
    ("Discover how to get a job in prescribed fire with the U.S. Fish and Wildlife Service.", 1),
    ("Life with winter foods is about so much more tham food it's about healthreating and weight control when fresh produce is available and difficult-get taste!", 0),
    ("Life with winter foods is about so much more than food: it's about healthy eating and weight control when fresh produce is less available and it's difficult to get outside!", 1),
    ("I would give the Xacto lazer trimmer two thumbs up but since the laser seems to be a bit touchy and has to me adjusted evey so often I will only give it 1 1/2 thuums up.", 0),
    ("I would give the Xacto laser trimmer two thumbs up but since the laser seems to be a bit touchy and has to be adjusted every so often I will only give it 1 1/2 thumbs up.", 1),
    ("Now, maybe it’s not going to be the greatest thing for our relations, but I feel that opinion of what I did say is honest and true, stroaight from my very heart.", 0),
    ("Now, maybe it’s not going to be the greatest thing for our relations, but I feel that what I did say was honest and true, straight from my very heart.", 1),
    ("Evna Daar is a Principal with Francisco Partners.", 0),
    ("Evan Daar is a Principal with Francisco Partners.", 1),
    ("Keep first use case that many people come across is segmentation of the network into “tiers ” (usually: three ) (, for example, being able to specify that back-end database tiers can only be accessed from application tier pods, not directly from the front end tier.", 0),
    ("The first use case that many people come across is segmentation of the network into “tiers” (usually three) — for example, being able to specify that a back-end database tier can only be accessed from application tier pods, not directly from the front-end tier.", 1),
    ("He worked as a war artist in England during World War II on his return to Montreal after the war he found the arts scene had changed, with the arrival of the automatists; when in prices which he he would move would be staying in the Laurentians.", 0),
    ("He worked as a war artist in England during World War II. On his return to Montreal after the war, he found that the arts scene had changed, with the arrival of the Automatistes. He left Montreal to live in the Laurentians.", 1),
    ("So; please advise to check product immediatly and using it so you have time to return..", 0),
    ("So please advising to check product immediately and use, so you have time to return..", 1),
    ("access mentors and to tell people who he or she should be a part of a knowledgeable community between like-minded.", 0),
    ("access mentors and be a part of a knowledgeable community of like-minded people.", 1),
    ("Removed some legacy settinglih that were no longer relevant as the dude users now controlled by ROS AAA.", 0),
    ("Removed some legacy setting that were no longer relevant as the dude users are now controlled by ROS AAA.", 1),
    ("We have lots of media updates so check them out of below!", 0),
    ("We have lots of media updates, so check them out below!", 1),
    ("So let's forget 802.11t with any open network.", 0),
    ("So let's forget about 802.11r with any open networks.", 1),
    ("Luke closed his eyes, knew about her commitment, loved her, knew her, and then laughed.", 0),
    ("Luke closed his eyes, knew her commitment, loved her, knew her, and then laughed.", 1),
    ("Always make sure you do your research before you dive so that you will know what type of sea life you’re likely to get in particular area.", 0),
    ("Always make sure you do your research before you dive, so that you will know what type of sea life you’re likely to encounter in a particular area.", 1),
    ("See how this his * all like a panda?", 0),
    ("See how this doesn't look at all like a panda?", 1),
    ("2. Have a mantra (and be sticked to you no matter what).", 0),
    ("2. Have a mantra (and stick with it, no matter what).", 1),
    ("Home» Account» Community» Account questions and rnswers» Can we begin my Project after my pro finished subscription end?", 0),
    ("Home» Account» Community» Account questions and answers» Can I use my finished Project after my pro subscription ended?", 1),
    ("Let me may encourage you to consider your parents in that.", 0),
    ("Let me encourage you to consider your parents in that.", 1),
    ("A permit of training does not represent acknowledge of lot line a fence.", 0),
    ("A permit to construct a fence does not constitute acknowledgment of the lot lines involved.", 1),
    ("On Thursday, August 27th, Superintendent Alberto Carvalho visited the school to celebrate the national recognition of the exelent educational oportunity here in Homestead.", 0),
    ("On Thursday, August 27th, Superintendent Alberto Carvalho, visited the school to celebrate the national recognition of the excellent educational opportunities here in Homestead.", 1),
    ("6+ years work experience in consulting marketing, growth or strategy.", 0),
    ("6+ years of work experience in marketing, growth or strategy consulting.", 1),
    ("As we work to inspire the next generation of Philanthropists we are proud to support We Act and We Day as testaments to the fact that individual actions could change humanity - partnership brings new possibilities to life.", 0),
    ("As we work to inspire the next generation of philanthropists, we are proud to support We Act and We Day, as testaments to the fact that individual action can change the world—and partnership brings new possibilities to life.", 1),
    ("The letter contained's no mention of current coach of Martino, who admitted to a disappointed season earlier this month when it seemed the team was no good chance of win championship in the league.", 0),
    ("The letter contained no mention of current coach Martino, who admitted to a disappointing season earlier this month when it seemed the team had no chance of winning the league.", 1),
    ("Home / Movies / Mia Wasikowska, th<) Alice in wonder land \"to Crimson peak \"", 0),
    ("Home / Movies / Mia Wasikowska, from \"Alice in Wonderland\" to \"Crimson Peak\"", 1),
    ("1. On Admin sidebar, tap Stores .Then With Setting, click Configuration.", 0),
    ("1. On the Admin sidebar, tap Stores. Then under Settings, click Configuration.", 1),
    ("Material type: Book; Format: print ; Literally form: Not fiction Publisher: Boston : International Press, 1998Availability Items available for loan: [Call Number: M 53 S963i v.4] (1).", 0),
    ("Material type: Book; Format: print ; Literary form: Not fiction Publisher: Boston : International Press, 1998Availability: Items available for loan: [Call number: M 53 S963i v.4] (1).", 1),
    ("In 2015 Team Health Holdings Inc. of Knoxville Tenn acquired IPC.", 0),
    ("In 2015, Team Health Holdings Inc. of Knoxville, Tenn., acquired IPC.", 1),
    ("A generation is bathed in self-esteem is a hard time who should integrate with institutional Christianity.", 0),
    ("A generation bathed in self-esteem is having a hard time integrating into institutional Christianity.", 1),
    ("ATC: Nov Charlie, turn to lead one-eight-zero and keep 3,000.", 0),
    ("ATC: Nov Charlie, turn to heading one-eight-zero and maintain 3,000.", 1),
    ("How to fit everyone in one picture.", 0),
    ("How to fit everyone in one picture?", 1),
    ("Grease with a small amount of butter (or oil spray) and stick ¼ cup of batter onto the pan", 0),
    ("Grease with a small amount of butter (or oil spray) and pour ¼ cup of batter onto the pan.", 1),
    ("for that Webpack is bundling it.", 0),
    ("for your particular application that Webpack is bundling.", 1),
    ("First full weekends in August. Don't miss you!", 0),
    ("First full weekend in August. Don't miss it!", 1),
    ("Most all science these days gets done over closed door, none of offices, other lab.", 0),
    ("Most science these days gets done behind closed doors, of offices, or labs, or whatever.", 1),
    ("It’s hardly surprising that a region that can practisely enjoy outstanding natural assets should offer some the country’s most suptuous local fare.", 0),
    ("It’s hardly surprising that a region that enjoys outstanding natural assets should also offer some of the country’s most sumptuous local fare.", 1),
    ("No Details There need to requirements, documents, or information needs for .co.ao?", 0),
    ("No Details Are there requirements, documents, or information needed for .co.ao?", 1),
    ("Lilibeth Gaydowen, NGCP’s Corporate Communications and Public Affairs officer for Noth Luzon said the specific cities and municipalities to be affected by the power interruption are done by said DU's, unless the activity affect the entire franchise area.", 0),
    ("Lilibeth Gaydowen, NGCP’s Corporate Communications and Public Affairs officer for North Luzon said the specific cities and municipalities to be affected by the power interruption are determined by the said DUs, unless the activity affects the entire franchise area.", 1),
    ("You probably could guess, but this used to be the old Osakis Creamery .We now use it for our offices and as our bottling facilities.", 0),
    ("You probably could guess, but this used to be the old Osakis Creamery. We now used it for our offices and as our bottling facility.", 1),
    ("View Full Version : How to navigate 5th Stes bikes land at Harvard?", 0),
    ("View Full Version : How to navigate 5th St bike lane at Harvard?", 1),
    ("Divade mixture of container and adds food coloring.", 0),
    ("Divide mixture into containers and add food coloring.", 1),
    ("Devils from my dream's.", 0),
    ("The angel from my dream.", 1),
    ("Alinta Energy will supply electricity, natural gas and solar energy to over 800,000 homes and business in Australia The Alinta has number of great value plan in fact it was awarded four Mozo Experts Choice Awards as best value electricity in 2018.", 0),
    ("Alinta Energy supplies electricity, natural gas and solar energy to 800,000 homes and businesses in Australia. Alinta has a number of great value plans, in fact it was awarded four Mozo Experts Choice Awards for best value electricity in 2018.", 1),
    ("What’s the one favorite they’re hoping to get?", 0),
    ("What’s the one souvenir they’re hoping to get?", 1),
    ("A application engineer can also choose to work in a computing domain that needs application of programming and software development that can help with develping computing systems and various software applications.", 0),
    ("An applications engineer can also choose to work in a computing domain that needs application of programming and software development that can help with developing computing systems and various software applications.", 1),
    ("17 Gurudas Nulkar (06/2016) Strategic Tangle: Cocreated Strategy Game for Management Students Management Teaching Review, : 1-8 ( ISSN: 2379-298).", 0),
    ("17 Gurudas Nulkar (06/2016) Strategic Tangle: A Cocreated Strategy Game for Management Students. Management Teaching Review, : 1-8 ( ISSN: 2379-2981).", 1),
    ("Firpo hoped the event would bridge the gap among bankers and professionals of Islamic financial industry and businessmen community hence it should be organised every year. \"The business community is keen to seek banking model which not only support their businesses but also multiply their investment on the principles of Sharia,\" he added.", 0),
    ("Firpo hoped the event would bridge the gap among bankers and professionals of Islamic financial industry and businessmen community hence it should be organised every year. \"The business community is keen to seek a banking model which not only support their businesses but also multiply their investment on the principles of Sharia,\" he added.", 1),
    ("The Jean Simpson Award was established to celebrate the life and achieve ments of the late Jean Simpson (1950-2002), a long time campaigner for flexible respite for families who are caring for a child with a disability, Jean’s influence and vision have left an only legacy at Interchange.", 0),
    ("The Jean Simpson Award was established to celebrate the life and achievements of the late Jean Simpson (1950-2002). A long time campaigner for flexible respite for families who are caring for a child with a disability, Jean’s influence and vision have left an on-going legacy at Interchange.", 1),
     ("A good understanding of the technology of digital photography gives you the knowledge you will need to get off the Auto setting and to gain much more control over your camera.", 1),
    ("Trisha, in her 16-year filmy career, has so far acted in Tamil, Telugu, Kannada, and Hindi industries, and now the actress is all set to make her entry into Malayalam. Let’s hope Trisha Krishnan finds success in Malayalam films as well.", 1),
    ("Find out more about Umina Beach.", 1),
    ("We, who have nothing better to do on a Sunday afternoon, demand answers!", 1),
    ("In this article, I’ll cover Service Versioning.", 1),
    ("September 14: Tito C. Band presented by Bubba Gump Shrimp Co.", 1),
    ("Using these methods, we can create different types of watercolor brushes for Photoshop using a scanner, watercolor paper, and paints. Please let me know if you have any other ideas??", 1),
    ("Remove unwanted hair on all parts of the body.", 1),
    ("Best admission paper editing sites gb, masters essay ghostwriters website uk, pay for mathematics bibliography, help with my life science essays, cheap mba homework examples. Definition essay topics death of a toad sample essay, best resume ghostwriter site for university, defining public relations essays.", 0),
    ("TFT will be respected for torrent transfers within each upload. When starting a new upload, the client is always chosen randomly, such that other networks will still get something.", 1),
    ("Published 04/25/2019 02:50:28 am at 04/25/2019 02:50:28 am in Shelf With Lamp.", 1),
    ("You will be given an antibiotic to prevent infection and a medication through your IV to relax you and make you drowsy, but it may not put you to sleep.", 1),
    ("My next show: tomorrow (Good Friday) 9pm to midnight.", 1),
    ("All translations (standard and sworn) are carried out by translators who translate into their native language and have superior knowledge of the source language.", 1),
    ("Thanks to John Casablancas and everyone at the Atlanta John Casablancas Center. Because of you, I'm a confident and self-sufficient person who is not afraid of the future.", 1),
    ("Both were forced to resign last fall after racist texts were discovered — even as an investigation into the pair’s financial conduct, as well as that of district solicitor James Ellison, was already underway.", 1),
    ("The opportunity to apply for jobs is exclusively offered to course graduates, subject to final grades, references, and employer recruitment processes.", 1),
    ("In December, the federal Agriculture Improvement Act removed hemp from the Controlled Substance Act, which means it is no longer illegal.", 1),
    ("What are some common symptoms of indoor air pollution?", 1),
    ("If you are dead set on getting a parts-only car, we’ve got some tips to protect you.", 1),
    ("Explaining strengths and weaknesses of individual providers so that you can make an accurate comparison between Embracia in Reservoir and other nursing homes in the Reservoir area. We can also provide you with a checklist of important features that should be considered.", 1),
    ("Try this website... paradisebeachvillas.com to view a very nice timeshare right in the middle of Eagle Beach. There is an owner/guest type board at: arubaparadisebeachvillas@groups.msn.com BEV.", 1),
    ("To improve processing of applications, the Province of Manitoba launched MPNP Online in June 2011, and after two years of positive feedback, the MPNP eliminated paperwork entirely, giving Manitoba the country’s first online-only immigration process.", 1),
    ("You'll need a PayPal account to tip Volksswitch. Click the button below and you will be redirected to PayPal. Once the payment is complete, you'll be brought back to Thingiverse.", 1),
    ("Absent the NBA's age requirement, it's unlikely Mayo or Rose would have played a nanosecond of college ball.", 1),
    ("Browse more Retaining Wall Construction Projects or H-Beam Installation Projects.", 1),
    ("The scrapping of ‘failing’ and ‘coasting’ schools, unless recognized as such by Ofsted, also shows how the tide is turning away from the payment by results regimes of the past quarter century since Ofsted replaced HMI.", 1),
    ("Which provisions of Title II of the ADA apply to websites?", 1),
    ("This product has a FreakScore of 6.8 out of 10 based on 3594 scores.", 1),
    ("What is the special unit being used to house the infected patients?", 1),
    ("Summer Vocal Program Registration is now OPEN! New offering: Disney Themed Vocal Camp the week of June 23.", 1),
    ("Medical giving Homecare Association written notice of non-compliance.", 1),
    ("At the weekend, his fellow islander from last year’s series accused the show of being staged and producers of setting up conversations.", 1),
    ("She will have surgery on 17th September to remove as much of it as possible and what happens after that is yet to be decided.", 1),
    ("The wildlife documentary series with David Attenborough continues with a unique and intimate glimpse into the secretive lives of mountain-dwelling animals.", 1),
    ("U+1D23F was added to Unicode in version 4.1 (2005). It belongs to the block Ancient Greek Musical Notation in the Supplementary Multilingual Plane.", 1),
    ("On Mondays between 6:00 and 12:00, the prices of products from the Veterinary Science product range in the 'Books' product group are on average around 1.7% lower than their respective average weekly price.", 1),
    ("There is no limit to the number of people who could view a book.", 1),
    ("Paty particularly enjoys brainstorming new ideas with colleagues across disciplines, and then implementing those ideas in her research and her writing. 'I love when I'm able to sit down and write a paper, because it crystallizes an idea for me,' she says.", 1),
    ("Contribute to your alma mater to help keep it relevant and secure.", 1),
    ("Is a bottle of dried laments.", 0),
    ("Configures your S3 user keys and optionally a GPG encryption key and whether to use HTTP or HTTPS for secure transport.", 1),
    ("This analysis tests the hypothesis that changes in nutrient loads, imbalances in nitrogen: phosphorus, and changes in nitrogen form, especially shifts to increasing loads of chemically reduced, rather than oxidized nitrogen, can have major impacts on food webs, from primary producers through secondary producers to fish.", 1),
    ("1kg Potatoes / 400g Onion Sets Multibuy Offer!", 1),
    ("Here is the Case I Landing Tips Paper.", 1),
    ("In this exact case, the fact remains this domain name is NOT a UBU. A ten-second phone call would have proven that.", 0),
    ("Instyle's Makeover issue for September 2012 addresses the rebirth of gray polish trends for fall.", 1),
    ("Tammy Schoonover: Great Site!!!! In just a few minutes of posting my info, I got my first call..... within the first 24 hrs, I had at least 8 calls, and over a dozen emails from interested companies!!! Thanks so much, I'm going to be starting with my new company next week!!!!", 1),
    ("King Road Church in Abbotsford, B.C., has traditionally hosted a family carnival, Fall Extravaganza, as a Halloween alternative.", 1),
    ("October 31, 2017: 667 the neighbor of the beast | See the playlist | Listen: Pop‑up player!", 1),
    ("What is considered a medical amount of CBD?", 1),
    ("However, with the news Peloton has opened a new production studio in New York City, dedicated to creating yoga and meditation classes for customers to follow in person or from the comfort of their own homes, it seems SoulCycle isn’t the only fitness industry leader in Peloton’s crosshairs.", 1),
    ("Promote Phonics Games and Earn Money.", 1),
    ("No Eriksen or Alli in the odds?", 1),
    ("I don’t think I have come across one of these before, it’s beautiful!", 1),
    ("The speaker comes in a box with a micro USB cable and with the Floatie which is a new accessory.", 1),
    ("No, it is not against the rules, and the sequence of events you followed is acceptable within a single Movement Phase.", 1),
    ("The Reds boss praised Allen's 'brilliant' performance in the 4-1 win over Stoke on Sunday, but admits he had to take him off because he is not yet '100 per cent fit'.", 1),
    ("However, just because you can do anything in music doesn’t mean you should.", 1),
    ("All rates are inclusive of 7% government tax.", 1),
    ("GOOD NEWS! We have many sponsors who may be willing to pay for a student to attend and get full reimbursement for tuition.", 1),
    ("Get our Gold hosting package for as little as £9.99/mon when you buy 1 years worth of hosting!", 1),
    ("Photo: Matthew Bull is a member of the under 12 NSW Cross Country Ski Team.", 1),
    ("The exhibition is the second phase of a three-year plan following the redevelopment of the original steam engine rooms in 2017 that powered the lifting mechanism until replaced by electric power in 1976.", 1),
    ("For more helpful insights on how to navigate situations in and out of the workplace, be sure to check out the many resources offered by GetFive.", 1),
    ("Why Did Jesus Never Mention the Millennium Temple?", 1),
    ("2. Take the original radio out of the dash by pulling the removal tools a little and pulling it out with your hands.", 1),
    ("Would you like to help girls feel good enough about themselves and their changing bodies to stay in school?", 1),
    ("My aunt made this AMAZING & DELICIOUS woodland themed cake!!!!!!!! Isn't it AWESOME???", 1),
    ("Cotton-and-polyester jacket ($644) by Oliver Spencer; cotton khakis ($65) by Dockers; leather shoes ($310) by Grenson.", 1),
    ("This is an event not to be missed, tickets are selling out so make sure to book now!", 1),
    ("The results of the midterm election confirm Americans’ widespread discontent with Washington gridlock on a range of issues.", 1),
    ("The attention to details and use of solid natural materials, marble, wood, copper and glass, in addition to superb craftsmanship, makes the building unmistakably Aalto.", 1),
    ("I was invited to review Bellota.", 1),
    ("The Animation Department at Emily Carr University is composed of multiple labs offering facilities to support a range of digital and traditional animation processes.", 1),
    ("But it postponed, without explanation, the planned launch in May of another satellite called Fajr.", 1),
    ("Reconstitute fruit juice and soups with less water.", 1),
    ("The beauty of the region is a lure to creative people, such as award-winning potter Ben Richardson, while historic buildings are another attraction.", 1),
    ("From Amblers Estate Agents - Chesterfield and 4 other top-performing local agents.", 1),
    ("Introvert entrepreneurs can use this technology boon to their advantage and succeed.", 1),
    ("Meanwhile, the West Indies team is considering a tour of Pakistan for two Twenty20s in March this year, subject to security clearance from the West Indies Players’ Association (WIPA), after receiving a proposal and security plan from the Pakistan Cricket Board (PCB).", 1),
    ("The number of players prescribing to the 'Gambler's Fallacy' in this thread is amusing. 'Try again later.' 'Do something else and then try again.' 'I have better luck at X time.'", 1),
    ("Design and Construction Program Manager: Northeastern US State Utility Company, New Haven & Bridgeport, CT - Smart Grid Network Protector Communication for 480V sidewalk vault transformation – Considering design and construction management to install and commission a fiber optic and wireless NERC CIP compliant communication system with SCADA controlin 13.8kv to 480V transformation network transformers across multiple locations in the city of New Haven, CT and Bridgeport, CT.", 0),
    ("Design and Construction Program Manager: Northeastern US State Utility Company, New Haven & Bridgeport, CT: Smart Grid Network Protector Communication for 480V sidewalk vault transformation – Responsible for design and construction management to install and commission a fiber optic and wireless NERC CIP compliant communication system providing SCADA control of 13.8kv to 480V transformation network transformers across multiple locations in the city of New Haven, CT and Bridgeport, CT.", 0),
    ("Our 24 hour packages is put the perfect way to get The most from you team in an away day.", 0),
    ("Our 24 hour packages are the perfect way to get the most from your team for an away day.", 1),
    ("Is Karn Sharma the answer to controlling India’s spin conundrum?", 1),
    ("Messi ends where Chelsea leave a cold towards Barcelona.", 0),
    ("Messi ends Chelsea drought to give Barcelona last-16 edge.", 1),
    ("To do that, return to the first method Changing Your Network Adapter’s Drivers but when you takes step three, select Search automatically for updated driver software and allow Windows to do the legwork.", 0),
    ("To do that, return to the first method — Changing Your Network Adapter’s Drivers — but when you get to step three, select Search automatically for updated driver software and then allow Windows to do the legwork.", 1),
    ("I find out this that should read this hand information along with'Management' Management’s Discussion and Analysis of Financial Condition and Results of Operations 'and our consolidated financial statements and related notes included as in this prospectus.", 0),
    ("You should read this information together with “Management’s Discussion and Analysis of Financial Condition and Results of Operations” and our consolidated financial statements and the related notes included elsewhere in this prospectus.", 1),
    ("The trump administration has not finally released final tariff list, but expected to do so later on Monday.", 0),
    ("The Trump administration has not yet released its final tariff list, but is expected to do so later on Monday.", 1),
    ("so is a grate crass if you want to build strength the 'yoga' way.", 0),
    ("So is a great class if you want to build strength the 'yoga' way.", 1),
    ("Here are the symptoms that guide you and make you test it by peeing it all in the your stick to.", 0),
    ("Here are the symptoms that will guide you and make you test it by peeing on the stick.", 1),
    ("lamb rack recipes lamb rack with a herb carut and vegetables best lamb rack reciep nz.", 0),
    ("lamb rack recipes lamb rack with a herb crust and vegetables best lamb rack recipe nz.", 1),
    ("France's announcement came a day after Swedish carmaker Volvo said it wil phase out petrol-only car until 2019.", 0),
    ("France's announcement came a day after Swedish carmaker Volvo said it will completely phase out petrol-only cars by 2019.", 1),
    ("Spacial matters faithfully alter infinity!", 0),
    ("Space matters faithfully alter infinity!", 1),
    ("Provide advice and assistance to managers and supervisors in the concepts, practices and procedures involved in developing submitting and justifying employee award.", 0),
    ("Provide advice and assistance to managers and supervisors in the concepts, practices and procedures involved in developing submitting and justifying employee award nominations.", 1),
    ("Many mental illness people experience challenges in their social and professional environments and subsequently may lose their life partner, family connection, friend, job or business; and ability to pay for treatment.", 0),
    ("Many people with mental disorders experience challenges in their social and professional environments and subsequently may lose their life partner, family connection, friends, job or business and the ability to pay for treatment.", 1),
    ("In the event you don’t need to purchase completely new LQM New A1322 battery for Apple Macbook Pro 13 inch A1278 A1322 [2009 2010 2011 Version] Battery 020-6547-A 661-5229 661-5557-12 Months warranty (A1322) by means of big value, you can sequence product by our purchase.", 0),
    ("In the event you don’t need to purchase the completely new LQM New A1322 Battery for Apple Macbook Pro 13 inch A1278 A1322 [2009 2010 2011 Version] Battery 020-6547-A 661-5229 661-5557-12 Months Warranty (A1322) by means of big value, you can sequence product by our purchase.", 1),
    ("All properties advertised for sale in Scotland must have a Home Report, comprising of a Single Survey,I EPC and a Property Questionnaire by the owner of Picture Frame and presentation of information of the property to potential purchasers.", 0),
    ("All properties advertised for sale in Scotland must have a Home Report, comprising of a Single Survey, EPC and a Property Questionnaire. The Property Questionnaire is completed by you, the owner, and displays information about the property to potential purchasers.", 1),
    ("I guess wherever I go, because I have to buy Center Ice.", 0),
    ("I guess wherever I go, I will have to buy Center Ice.", 1),
    ("Both have written that they are concerned that 1992 action plan backed by the United Nations — to promote sustainable development — is being embraced by local authorities.", 0),
    ("Both speakers have written that they are concerned that a 1992 action plan backed by the United Nations — one that promotes sustainable development — is being embraced by local governments.", 1),
    ("Did by RiverTown Newsroom in Jan 31, 2019 at 6:00 a.m.", 0),
    ("By RiverTown Newsroom on Jan 31, 2019 at 6:00 a.m.", 1),
    ("Hi there - I&rsquo;m wondering if it&rsquo;s possible to shipe this in New Zealand? I am reside in New Hampshire but will like to send it as a gift to my sister in NZ what would to the shiping to be as?", 0),
    ("Hi there - I&rsquo;m wondering if it&rsquo;s possible to ship this to New Zealand? I reside in New Hampshire but would like to send it as a gift to my sister in NZ. What would the shipping cost be?", 1),
    ("The result is more dynamic, prodigious bass throughout the room while reached over a half octave below the S.5 model.", 0),
    ("The result is more dynamic, prodigious bass across the entire room while reaching over a half octave below the S.5 model.", 1),
    ("I'll be very interested see how this pans out.", 0),
    ("I'll be very interested to see how this pans out.", 1),
    ("There’ll be's two, “Special Assortment” boxes, containing three lots of foursome are “Chocolatory Special” series chocolates, with one featuring the lucky image of Ebisu, the most god of fishermen and luck, is especially located on business purposes, and another emazoned whith the word “Ookini“, which means “thank you” in Osaka’s Kansai-region dialect.", 0),
    ("There’ll be two “Special Assortment” boxes, containing three lots of four “Chocolatory Special” series chocolates, with one featuring the lucky image of Ebisu, the god of fishermen and luck, especially appropriate for business purposes, and another emblazoned with the word “Ookini“, which means “thank you” in Osaka’s Kansai-region dialect.", 1),
    ("The Travel Management Company’s role is to be the connection to the NDC content and create processes to unify all content in a easy-to-use workflow for improved service offering to the Corporate Business Traveler The TMC has their own proprietary tools that include scripting, mid and back office platforms which will all be impacted by the NDC technology changes – thus requiring the TMC to stay ahead of the anticipated ones.", 0),
    ("The Travel Management Company’s role is to be the connection to the NDC content and create processes to unify all content in an easy-to-use workflow for improved service offerings to the Corporate Business Traveler. The TMC has their own proprietary tools that include scripting, mid- and back-office platforms, which will all be impacted by the NDC technology changes – thus requiring the TMC to stay ahead of the anticipated changes.", 1),
    ("Iron serbian was at hand to capture the destruction in the video below.", 0),
    ("Iron Serbian was on hand to capture the destruction in the video below.", 1),
    ("Video's and is no longer avaible?", 0),
    ("This video is no longer available?", 1),
    ("For more information about AFA Teens and fo enter the scholarship competition, visit. www.youngleadersofafa.org/ or call 866-232-8484.", 0),
    ("For more information about AFA Teens and to enter the scholarship competition, visit www.youngleadersofafa.org/ or call 866-232-8484.", 1),
    ("HUNTINGODN: A builder was contracted for six years to steal from suppliers and customers under running a string of construction and property companies under aliasing.i aliasue line.", 0),
    ("HUNTINGDON: A builder has been jailed for six years for stealing from suppliers and customers while running a string of construction and property companies under a series of aliases.", 1),
    ("deems in to have resigned.", 0),
    ("Shall be deemed to have resigned.", 1),
    ("OpenLabs will have releasing an Apple OS X supported platforms in early 2012.", 0),
    ("Open Labs will be releasing an Apple OS X supported platform in early 2012.", 1),
    ("Stephanopoulos told Sanders of bar, thinking that a single news article that she mentioned did n't back up the president’s claim and ask her for actual evidence. (?)", 0),
    ("Stephanopoulos cut Sanders off, saying that not a single news article that she mentioned backs up the president’s claim and asking her for actual evidence.", 1),
    ("Also hailing from Wales UK are Jay Aston’s Gene Loves Jezebel, who first broke into American charts in 1985 with a cocktail of infective hit songs such as ‘Desire’, ‘Jealous’ and ‘The Motion Of Love’, and would be joining Sigma LXXXV Tour in support of their most recent album release, Dance Underwater which was received with deligtby their legion of fans.", 0),
    ("Also hailing from Wales UK, are Jay Aston’s Gene Loves Jezebel, who first broke onto the American charts in 1985 with a cocktail of infectious hit songs such as ‘Desire’, ‘Jealous’ and ‘The Motion Of Love’, and will be joining the Sigma LXXXV Tour in support of their most recent album release, Dance Underwater which was received with delight by their legion of fans.", 1),
    ("Why do you think stories of human beings in music, movies, novels and other forms of expression are dominated by topic that the speaker describes as “dark?: How dose the song of Lamech in Genisis 4:24-25 compare?", 0),
    ("Why do you think the stories of human beings in music, movies, novels and other forms of expression are dominated by themes that the speaker describes as “dark”? How does the song of Lamech in Genesis 4:24-25 compare?", 1),
    ("I use it about 3-4 times, approx 1-15 mins each.", 0),
    ("I've used it about 3-4 times, approx 10-15 mins each time.", 1),
    ("Which is exactly what I felt when I picked up a copy of Top Ten of Shark Deadly Shos theme and learned that the Discovery Channel was getting in comics. /", 0),
    ("Which is precisely what I felt when I picked up a copy of The Top Ten Deadliest Sharks and learned that the Discovery Channel was getting into comics.", 1),
    ("Wait until hi every my all persons, we merely launched fresh real racing 3 hack cheat tool which usually will give you Real Racing 3 hacking script process done.", 0),
    ("Wait until hi every person, we merely launched fresh real racing 3 hack cheat tool which usually will give you Real Racing 3 hacking script process done.", 1),
    ("The state of Plateau is among the states of Nigeria that is running currently on deficit according to BudgIT that is really unfortunate because this state is among the few in Nigeria that has a double in the sense that it have huge deposit of solid minerals with export potential in addition to it estimate agricultural potential.", 0),
    ("The state of Plateau is among the states in Nigeria that is currently running on deficit according to BudgIT. This is really unfortunate because this state is among the few in Nigeria that has a double in the sense that it has huge deposit of solid minerals with export potential in addition to its agricultural potential.", 1),
    ("Picturing with my Rossignol Sky7 HD 188cm.", 0),
    ("Pictured with my Rossignol Sky7 HD 188cm.", 1),
    ("Bicyccl Crate Parts/Accessory shop the largest and noteable affordable!", 0),
    ("Bicycle Crate Parts/Accessories shop the largest and most affordable!", 1),
    ("Puma by design: Courtesy of the dysfunction in the present administration, your current enemies had been involved in a war with us on U.S. soil having an authority of refusing to be told what you wishing to give a good name to him while they at the same time, was concerned.", 0),
    ("Puma By Design: Courtesy of the dysfunction in the present administration, America’s enemies are at war with us on U.S. soil empowered by our so-called leaders who are in denial, stupid and in the pockets of our enemies while at the same time, refusing to call this evil by its name.", 1),
    ("Till now you learn your english with your eyes ^ ^ school you most probably learn through your eyes you read Text books ^ that’s why you read well but cannot speak well, for example you can easily understandwriting english but you do not easily Real English Speaking that giss what we are going to teach you How To Learn Spoken English.", 0),
    ("Till now you learn your English with your eyes, in school you most probably learn through your eyes you read Text books, that’s why you read well but cannot speak well, for example you can easily understand written English, but you do not easily Real English Speaking. That is what we are going to teach you How To Learn Spoken English.", 1),
    ("Please remind us that both LEXIA and iready can be worked on at home.", 0),
    ("Please remember that both Lexia and iready can be worked on at home.", 1),
    ("However, it also causes infinite loop if you get a messy redirection, so a wise person would limit the number of redirects to follow.", 0),
    ("However, it also causes infinite loops if you get a messy redirection, so a wise person would limit the number of redirects to follow.", 1),
    ("Columbia Use Auto Parts, Inc.", 0),
    ("Columbia Used Auto Parts, Inc.", 1),
    ("How successful was the book at ringing the popular focus to slavery?", 0),
    ("How successful was the book at bringing the popular focus to slavery?", 1),
    ("Florida Statute §489.129(i) (2006) though only allowed the DBPR (and not Courts) to take administrative action (and not ciivl action) if a Contractor fails in any materials respect to comply with the provisions of Chapter 489.", 0),
    ("Florida Statute §489.129(i) (2006) only seems to allow the DBPR (and not Courts) to take administrative action (and not civil action) if a Contractor Fail[ed] in any material respect to comply with the provisions of Chapter 489.", 1),
    ("With back to back Android 4.3 sightings for the Nexus 4 spotted, it can only mean that Google are almost ready to go live with an official download for the public with the Nexus 4 first in line thanks to the stock user experience that Google offers as part of their Nexus incentive.", 0),
    ("With back to back Android 4.3 sightings on the Nexus 4 spotted, it can only mean that Google are almost ready to go live with an official download for the public, with the Nexus 4 first in line thanks to the stock user experience that Google offers as part of their Nexus incentive.", 1),
    ("Hit the link & Enter your the required details of candidate.", 0),
    ("Hit the link & Enter your the required details of the candidate.", 1),
    ("Click here to read it in 'Acoustic Treatments Explained'! IndiePulse - Music Zine a Journalistic M News Magaine Online with great Reviews and Interviews.", 0),
    ("Click here to read the article 'Acoustic Treatments Explained'! IndiePulse is a Music Zine, a Journalistic and Music News Magazine Online, with great Reviews and Interviews.", 1),
    ("Add all your fixings Gordita!!!!!!!…beans, cheese, lettuce, salsa, sour cream, guacamole; whatever you like!", 0),
    ("Add all your fixings to your Gordita…beans, cheese, lettuce, salsa, sour cream, guacamole; whatever you like!", 1),
    ("Note 2: If palmaris longus tendon is not present, PC5 has medal with the flexor carpi radialis tendon.", 0),
    ("Note 2: If the palmaris longus tendon is not present, PC5 is medial to the flexor carpi radialis tendon.", 1),
    ("Duration of antiebacteries at MI is 7-10 days.", 0),
    ("Duration of antibacterial therapy at MI is 7-10 days.", 1),
    ("Codlts D is ranked 10th.", 0),
    ("Colts D is ranked 10th.", 1),
    ("You can have hands-on experience with for the whole SDLC: Requirement, Design, Code, Test, Deploy", 0),
    ("You have hands-on experience with the whole SDLC: Requirement, Design, Code, Test, Deploy.", 1),
    ("The opinions of this article are those of the writer and may not reflect those of Mud Run Guide.", 0),
    ("The opinions in this article are those of the writer and may not reflect those of Mud Run Guide.", 1),
    ("Your code must poduce good output in more images but for them, you must test your code in this test set of images and upload your output.", 0),
    ("Your code must produce good output on most images in general, but, for this challenge, you must test your code on this test set of images and upload your output.", 1),
    ("make children around the world give sonthimg to smile ^ a new chance at life.", 0),
    ("Give children around the world something to smile about – a new chance at life.", 1),
    ("Isaiah Hicks made a jumper Assisted by Joel Berry II.", 0),
    ("Isaiah Hicks made Jumper. Assisted by Joel Berry II.", 1)
]

data = [{'sentence': sentence, 'classification': classification} for sentence, classification in sentences_data]

with open('sentences_data.json', 'w') as json_file:
    json.dump(data, json_file, indent=4)

sentences = [entry['sentence'] for entry in data]
labels = [entry['classification'] for entry in data]

"""The code initializes necessary libraries and imports such as json, numpy, tensorflow, sklearn modules for machine learning, and transformers for BERT model integration. It defines a list sentences_data containing example sentences paired with binary classifications, which is then structured into a JSON format and saved as sentences_data.json. This data is then loaded back into sentences and labels lists for further processing."""

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertModel.from_pretrained('bert-base-uncased')

max_length = 128
tokenized_sentences = tokenizer(sentences, padding='max_length', truncation=True, max_length=max_length, return_tensors='tf')

bert_outputs = model(tokenized_sentences)
bert_embeddings = bert_outputs.last_hidden_state

"""The code utilizes the BERT tokenizer (BertTokenizer) from the 'bert-base-uncased' pre-trained model to tokenize the sentences and prepare them for embedding. The BERT model itself (TFBertModel) is also loaded to generate embeddings for each tokenized sentence. The maximum sequence length for padding and truncation is set to 128 tokens. The tokenized sentences are fed into the BERT model to obtain embeddings (bert_embeddings), which represent each sentence as a sequence of vectors.


"""

print("Shape of bert_embeddings:", bert_embeddings.shape)
print("Type of labels:", type(labels))
print("Length of labels:", len(labels))

y = np.array(labels)
bert_embeddings_np = np.array(bert_embeddings)

"""The shape of bert_embeddings is printed to verify its dimensions, followed by the type and length of labels. The labels list is converted into a NumPy array y for compatibility with scikit-learn. bert_embeddings is also converted to a NumPy array bert_embeddings_np for subsequent operations.


"""

X_train, X_test, y_train, y_test = train_test_split(bert_embeddings_np, y, test_size=0.2, random_state=42)
X_train_flattened = tf.reshape(X_train, (X_train.shape[0], -1))
X_test_flattened = tf.reshape(X_test, (X_test.shape[0], -1))
model_lr = LogisticRegression()
model_lr.fit(X_train_flattened, y_train)
y_pred = model_lr.predict(X_test_flattened)

"""The dataset is split into training and testing sets using train_test_split from scikit-learn, with 20% reserved for testing and a specified random state for reproducibility. The embeddings in bert_embeddings_np are reshaped into flattened arrays (X_train_flattened and X_test_flattened) to meet the input requirements of the logistic regression model (LogisticRegression)"""

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
report = classification_report(y_test, y_pred)
print(report)

"""A logistic regression model (model_lr) is instantiated and trained on the flattened training data (X_train_flattened and y_train). The model then predicts labels (y_pred) for the test data (X_test_flattened), and the accuracy of these predictions is computed using accuracy_score. Additionally, a classification report (report) is generated to provide precision, recall, F1-score, and support metrics for each class in the test set."""